@startuml ParkPlan

package HomePage {
  [HomePage.js] - [homepage.css]
  [HomePage.js] ..> [Welcome.jsx]
  [HomePage.js] ..> [Explore.jsx]
  [HomePage.js] ..> [Buttons.jsx]
  [HomePage.js] ..> [HighlightGallery.jsx]
  
}

package ParkInfo {
  [ParkInfo.js] - [parkinfo.css]
  [ParkInfo.js] ..> [ParkInfoComponent.jsx]
}

package ParkSearch {
  [ParkSearch.js] - [parkSearch.css]
  [ParkSearch.js] ..> [ParkSearchWelcome.jsx]
  [ParkSearch.js] ..> [ActivitiesList.jsx]
  [ParkSearch.js] ..> [FetchParks.js]
  [ParkSearch.js] ..> [Activities.js]
}

package GlobalComponents {
  [Navbar.jsx] - [navbar.css]
  [Footer.jsx]
}

GlobalComponents <|-down- HomePage
GlobalComponents <|-down- ParkInfo
GlobalComponents <|-down- ParkSearch
'HomePage .up.> GlobalComponents
'ParkInfo .up.> GlobalComponents
'ParkSearch ..> GlobalComponents

'[Welcome.jsx] ..> [Navbar.jsx]
'[Explore.jsx] ..> [Navbar.jsx]
'[Buttons.jsx] ..> [Navbar.jsx]
'[ParkInfoComponent.jsx] ..> [Navbar.jsx]
'[ParkSearchWelcome.jsx] ..> [Navbar.jsx]
'[ActivitiesList.jsx] ..> [Navbar.jsx]

'[Welcome.jsx] ..> [Footer.jsx]
'[Explore.jsx] ..> [Footer.jsx]
'[Buttons.jsx] ..> [Footer.jsx]
'[ParkInfoComponent.jsx] ..> [Footer.jsx]
'[ParkSearchWelcome.jsx] ..> [Footer.jsx]
'[ActivitiesList.jsx] ..> [Footer.jsx]

'[public/index.html] -right-> [HomePage.js]
'[public/index.html] -right-> [ParkPlan.js]
'[public/index.html] -right-> [ParkInfo.js]
'[public/index.html] -right-> [ParkSearch.js]

'[React] -up-> [index.js]
'[React Router] -up-> [index.js]

'index.js -right-> [Navbar.jsx]
'index.js -right-> [Footer.jsx]

@enduml
