@startuml Park Plan Sequence
title Park Plan Sequence

actor User
participant HTML
participant "ReactComponent/JS" as RCJS
participant "Temple News API (backend)" as TUAPI

activate User
activate HTML

User -> HTML : HTTP Request
User <-- HTML : HTTP Response

HTML -> RCJS: loads
activate RCJS

RCJS -> RCJS : useEffect()
RCJS -> TUAPI : asynchronous fetch()
activate TUAPI

RCJS <-- TUAPI : json of Temple News
deactivate TUAPI

HTML <-- RCJS: updates page
deactivate RCJS

User -> HTML: rates individual park

HTML -> RCJS: Loads
activate RCJS

RCJS -> RCJS: StarRating()
HTML <-- RCJS: updates page
deactivate RCJS


@enduml
